In [34]:
import numpy as np
from sklearn.neural_network import MLPClassifier

# Step 1: Define digit patterns (5x3) as binary matrices
digits = {
    0: [
        [1, 1, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 1, 1],
    ],
    1: [
        [0, 1, 0],
        [1, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 1, 1],
    ],
    2: [
        [1, 1, 1],
        [0, 0, 1],
        [1, 1, 1],
        [1, 0, 0],
        [1, 1, 1],
    ],
    39: [
        [1, 1, 1],
        [0, 0, 1],
        [0, 1, 1],
        [0, 0, 1],
        [1, 1, 1],
    ]
}

# Step 2: Prepare training data
X = []
y = []

for label, matrix in digits.items():
    flat = np.array(matrix).flatten()
    X.append(flat)
    y.append(label)

# Step 3: Train the model
clf = MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000, random_state=42)
clf.fit(X, y)

# Step 4: Recognition function
def recognize_digit(matrix):
    flat = np.array(matrix).flatten().reshape(1, -1)
    print(flat)
    prediction = clf.predict(flat)
    return prediction[0]

# Step 5: Test all digit matrices
print("=== Testing All Numbers ===")
for label, matrix in digits.items():
    result = recognize_digit(matrix)
    print(f"Expected: {label}, Recognized: {result}")


=== Testing All Numbers ===
[[1 1 1 1 0 1 1 0 1 1 0 1 1 1 1]]
Expected: 0, Recognized: [0]
[[0 1 0 1 1 0 0 1 0 0 1 0 1 1 1]]
Expected: 1, Recognized: [1]
[[1 1 1 0 0 1 1 1 1 1 0 0 1 1 1]]
Expected: 2, Recognized: [2]
[[1 1 1 0 0 1 0 1 1 0 0 1 1 1 1]]
Expected: 39, Recognized: [39]
