In [1]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Sigmoid derivative (used for backpropagation)
def sigmoid_derivative(x):
    return x * (1 - x)

# Backward propagation
def backward_propagation(X, y, hidden_layer_output, predicted_output, hidden_weights, output_weights, hidden_bias, output_bias, learning_rate):
  
    # Step 1: Compute error (difference between expected and predicted output)
    error = y - predicted_output
    
    # Step 2: Compute derivative of the output layer
    d_predicted_output = error * sigmoid_derivative(predicted_output)
    
    # Step 3: Compute error for hidden layer
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)
    
    # Step 4: Update weights and biases using gradient descent
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    hidden_weights += X.T.dot(d_hidden_layer) * learning_rate
    hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate
    
    return hidden_weights, hidden_bias, output_weights, output_bias

# Example usage (for XOR problem)
if __name__ == "__main__":
    # Input data (XOR problem)
    X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
    y = np.array([[0], [1], [1], [0]])  # XOR output
    
    # Randomly initialized weights and biases
    hidden_weights = np.random.uniform(size=(X.shape[1], 4))  # 4 neurons in hidden layer
    hidden_bias = np.random.uniform(size=(1, 4))
    output_weights = np.random.uniform(size=(4, 1))  # 1 neuron in output layer
    output_bias = np.random.uniform(size=(1, 1))
    
    # Forward propagation to get hidden layer output and predicted output
    hidden_layer_activation = np.dot(X, hidden_weights) + hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)
    output_layer_activation = np.dot(hidden_layer_output, output_weights) + output_bias
    predicted_output = sigmoid(output_layer_activation)
    
    # Perform backward propagation to update weights and biases
    learning_rate = 0.1
    hidden_weights, hidden_bias, output_weights, output_bias = backward_propagation(
        X, y, hidden_layer_output, predicted_output, hidden_weights, output_weights, hidden_bias, output_bias, learning_rate)
    
    # Output updated weights and biases
    print("Updated Output Weights:\n", output_weights)
    print("Updated Output Bias:\n", output_bias)
    print("Updated Hidden Weights:\n", hidden_weights)
    print("Updated Hidden Bias:\n", hidden_bias)


Updated Output Weights:
 [[0.2097756 ]
 [0.8157963 ]
 [0.94055857]
 [0.84703625]]
Updated Output Bias:
 [[0.63552511]]
Updated Hidden Weights:
 [[0.46921609 0.01393792 0.07399215 0.11076082]
 [0.59760735 0.82523475 0.90413039 0.30136059]
 [0.63406203 0.50269977 0.53290754 0.08100547]]
Updated Hidden Bias:
 [[0.7361879  0.21834027 0.16642478 0.21718861]]
